services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
    buildCommand: ""
    startCommand: "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
